apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "HelmCharts/MyChart1"
    repoURL: "git@github.com:ValeriiVasianovych/ArgoCD-Helm-Charts.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      # parameters:
      # - name: "image.name"
      #   value: nginx:latest

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         