apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    owner: {{ .Values.label.owner }}
    env: {{ .Values.label.env }}

spec:
  selector:
    app: {{ .Values.names.appName }}
  ports:
     - name: app-listener
       protocol: TCP
       port: 8080
       targetPort: 8080

  type: LoadBalancer